version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mcdonalds_db
    environment:
      MYSQL_DATABASE: mcdonalds_locations
      MYSQL_USER: Admin
      MYSQL_PASSWORD: Admin
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"

volumes:
  db_data: